### ISSUE TITLE
Bilibili CC字幕助手本地字幕问题

### ISSUE THREAD

**Issue by indefined** [indefined/UserScripts#6]
## TODO

- [x] ~~toast，关键操作和错误提示 resolved in 0b00ec8396d381de2f123fc05972fea82638b6a6 && little Off topic~~
- [ ] 解决薛定谔的本地字幕加载问题
  - 随机文件薛定谔般的随机发生
  - 捕捉不到错误，甚至无法进入调试断点
  - 重试可能就能正常加载了
  - 猜测没有触发`FileReader`的`onload`事件
- [x] ~~本地字幕选择操作界面 resolved in 3defdfaf493ee554932682ea86578063017d9040~~
- [x] ~~旧版设置面板兼容优化 Off topic && resolved~~
  - [x] ~~样式已兼容大部分视频页面 fixed in 99a4974900eca51d1d699a88cfbecaedba7ac3ba &&  Off topic~~
  - [x] ~~火狐无法下拉选择字幕和选项 fixed in cad634733305af84eeccc3791a52e6e80f08ef33~~

**Comment by indefined** [comment]
随机加载失败问题无法定位，暂挂起，有新发现请继续回复会重新打开问题
